### ISSUE TITLE
vbs bison parse conflicts

### ISSUE THREAD

**Issue by fooofei** [alexhenrie/wine#3]
my test vbscript case :
 createobject("wscript.shell").run "calc.exe"

this file  use vbs bison parse (https://github.com/alexhenrie/wine/blob/master/dlls/vbscript/parser.y),  parse result :
 fail at .run , because there has one conflict  , as blow show , 

run command 【bison -v -d -pparser_ parser.y】, generate file 【parser.output】,

part of the file show this conflict : 

state 160

   77 ArgumentList: Expression .
   78             | Expression . ',' ArgumentList
   85 Expression: Expression . tIMP EqvExpression
  138 PrimaryExpression: '(' Expression . ')'

```
tIMP  shift, and go to state 123
','   shift, and go to state 162
')'   shift, and go to state 156

')'  [reduce using rule 77 (ArgumentList)]
```

as we can see above ,  there has one shift/reduce conflict . to parse this case , we need a reduce to ArgumentList , not to shift to PrimaryExpression . 

hope someone give a solution , thanks .

**Comment by alexhenrie** [comment]
Please write a more clear bug report (with better grammar, spelling, and punctuation), submit it at https://bugs.winehq.org/, and CC Jacek Caban who maintains Wine's vbscript.dll.

**Comment by fooofei** [comment]
copy that, thanks, I will.
