### ISSUE TITLE
 wine/dlls/crypt32/base64.c

### ISSUE THREAD

**Issue by M2000Interpreter** [alexhenrie/wine#4]
Line 822 LPCWSTR trailer = CERT_TRAILER_START_W;
Should be
LPCWSTR trailer = CERT_TRAILER_W;

Because has to put 
-----END CERTIFICATE-----
I found this with this program http://georgekarras.blogspot.gr/2018/02/base64-using-crypt32-in-m2000-not-for.html 
using CRYPT_STRING_BASE64HEADER=0x0 (without altering to 0x1 to prevent error, but then missing headers)

**Comment by alexhenrie** [comment]
Please file a bug at https://bugs.winehq.org/ and add this code's author, Lauri Kenttä, to the CC list.
